config/routes.rb
Rails.application.routes.draw do
  resources :password_resets, only: [:new, :create]
  resource :session, only: [:new, :create, :destroy]
  resources :users, only: [:new, :create] do
    resources :password_resets, only: [:edit, :update]
  end
  resources :invitations, only: [:index]
  resources :permissions, only: [:create]
  resources :calendars do
    member do
      patch 'current_date'
    end
    resources :events, except: [:index, :show]
    resources :invitations, only: [:create, :destroy]
    resources :permissions, only: [:destroy]
  end
  match '/404', to: 'errors#not_found', via: :all, as: :not_found
  match '/500', to: 'errors#internal_server_error', via: :all, as: :internal_server_error
  root to: 'welcome#show'
end

app/models/calendar.rb
class Calendar < ApplicationRecord
  attribute :current_date, ArDate.new

  has_many :events, dependent: :destroy
  has_many :invitations, dependent: :destroy
  has_many :permissions, dependent: :destroy
  has_many :users, through: :permissions

  validates :current_date, presence: true
  validates :title, presence: true, length: { maximum: 100 }

  def events_for_month(around:)
    date = around
    start_date = date.beginning_of_month.beginning_of_week
    end_date = date.end_of_month.end_of_week
    month_range = start_date..end_date

    events.where(occurred_on: month_range)
  end
end

app/controllers/calendars_controller.rb
class CalendarsController < AuthorizedController
  layout 'calendar', only: :show

  def index
    @calendars = Calendar.
      joins(:permissions).
      where(permissions: { level: 'owner', user: current_user })
  end

  def show
    @calendar = Calendar.find(params[:id])
    @presenter = present(@calendar)
    raise CalendarNotFound if !current_user.can_view?(@calendar)
    @presenter.current_user = current_user

    if params[:date].present?
      @presenter.origin_date = ArDate.parse(params[:date])
    else
      @presenter.origin_date = @calendar.current_date
    end
  end

  def new
    @calendar = Calendar.new
  end

  def create
    @calendar = current_user.calendars.create(calendar_params)

    if @calendar.save
      permission = @calendar.permissions.find_by(user: current_user)
      permission.update(level: :owner)
      redirect_to calendar_path(@calendar)
    end
  end

  def edit
    calendar = current_user.calendars.find(params[:id])
    @calendar_presenter = present(:calendar_edit, calendar)
    raise NotAuthorized if !current_user.can_own?(calendar)
    @invitation = Invitation.new(calendar: calendar, owner: current_user)
  end

  def update
    @calendar = current_user.calendars.find(params[:id])

    if @calendar.update(calendar_params)
      redirect_to calendars_path
    end
  end

  def current_date
    @calendar = current_user.calendars.find(params[:id])
    current_day_params = params.permit(:current_date)

    if @calendar.update(current_day_params)
      redirect_to calendar_path(@calendar)
    end
  end

  def destroy
    @calendar = current_user.calendars.find(params[:id])

    if @calendar.destroy
      redirect_to calendars_path
    end
  end

  private

  def calendar_params
    params.require(:calendar).permit(:title)
  end
end

app/views/calendars/_form.html.erb
<%= simple_form_for(calendar) do |form| %>
  <%= form.input :title %>
  <div class="actions">
    <%= form.submit %>
    <% if calendar.persisted? %>
      <%= link_to(
        t('helpers.action.calendar.destroy'),
        calendar_path(calendar),
        method: :delete,
        data: { confirm: t('helpers.messages.calendar.confirm_delete') }
      ) %>
    <% end %>
  </div>
<% end %>

app/views/calendars/edit.html.erb
<%= render partial: 'form', locals: { calendar: @calendar_presenter.calendar } %>
<section class="permissions">
  <h3>Permissions</h3>
  <%= @calendar_presenter.permission_list %>
</section>
<section class="invitations">
  <h3>Invitations</h3>
  <%= @calendar_presenter.invitation_list %>
  <%= simple_form_for([@calendar_presenter.calendar, @invitation]) do |form| %>
    <%= form.input :owner_id, as: :hidden %>
    <%= form.input :calendar_id, as: :hidden %>
    <%= form.input :email %>
    <%= form.input :level, collection: permission_levels_for_select %>
    <%= form.submit %>
  <% end %>
</section>

app/views/calendars/index.html.erb
<ul class="calendars">
  <% @calendars.each do |calendar| %>
    <li>
      <span class="title"><%= calendar.title %></span>
      <%= link_to t('helpers.action.calendar.edit'), edit_calendar_path(calendar) %>
    </li>
  <% end %>
</ul>

app/views/calendars/new.html.erb
<%= render partial: 'form', locals: { calendar: @calendar } %>

app/views/calendars/show.html.erb
<section class="calendar">
  <nav>
    <%= @presenter.previous_month_link %>
    <%= @presenter.month_and_year %>
    <%= @presenter.next_month_link %>
  </nav>
  <div class="wrapper">
    <%= @presenter.day_names_header %>
    <% @presenter.calendar_weeks do |week| %>
      <div class="week">
        <% @presenter.week_dates(within: week) do |date| %>
          <div class="<%= @presenter.date_classes(date) %>">
            <header>
              <span class="number"><%= date.day %></span>
              <%= @presenter.today_action(on: date) %>
            </header>
            <%= @presenter.events(on: date) %>
            <%= @presenter.new_event_action(on: date) %>
          </div>
        <% end %>
      </div>
    <% end %>
  </div>
</section>