config/routes.rb
Rails.application.routes.draw do
  resources :password_resets, only: [:new, :create]
  resource :session, only: [:new, :create, :destroy]
  resources :users, only: [:new, :create] do
    resources :password_resets, only: [:edit, :update]
  end
  resources :invitations, only: [:index]
  resources :permissions, only: [:create]
  resources :calendars do
    member do
      patch 'current_date'
    end
    resources :events, except: [:index, :show]
    resources :invitations, only: [:create, :destroy]
    resources :permissions, only: [:destroy]
  end
  match '/404', to: 'errors#not_found', via: :all, as: :not_found
  match '/500', to: 'errors#internal_server_error', via: :all, as: :internal_server_error
  root to: 'welcome#show'
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Oath::ControllerHelpers
  protect_from_forgery with: :exception
end

app/helpers/application_helper.rb
module ApplicationHelper
  def form_error_hint(model)
    if model.errors.any?
      model_key = model.model_name.i18n_key
      error_count = pluralize(model.errors.count, 'error')
      if model.persisted?
        action = 'update'
      else
        action = 'create'
      end
      content_tag(
        :p,
        t("helpers.error.#{model_key}.#{action}", error_count: error_count),
        class: 'error-tip'
      )
    end
  end

  def date_from_day_number(day_number)
    ArDateParser.from_day_number(day_number.to_i)
  end

  def permission_levels_for_select
    Permission::INVITATION_LEVELS.map do |level|
      [level.titleize, level]
    end
  end
end

app/views/application/_analytics.html.erb
<% if ENV['GAUGES_KEY'].present? %>
  <script type="text/javascript">
  var _gauges = _gauges || [];
  (function() {
    var t   = document.createElement('script');
    t.type  = 'text/javascript';
    t.async = true;
    t.id    = 'gauges-tracker';
    t.setAttribute('data-site-id', '<%= ENV['GAUGES_KEY'] %>');
    t.setAttribute('data-track-path', 'https://track.gaug.es/track.gif');
    t.src = 'https://d2fuc4clr7gvcn.cloudfront.net/track.js';
    var s = document.getElementsByTagName('script')[0];
    s.parentNode.insertBefore(t, s);
  })();
  </script>
<% end %>

app/views/application/_flashes.html.erb
<% if !flash.empty? %>
  <ul class="flashes">
    <% flash.each do |name, message| %>
      <%= content_tag(:li, message, class: name) %>
    <% end %>
  </ul>
<% end %>

app/views/application/_javascript.html.erb
<script src="https://use.typekit.net/qot5kvk.js"></script>
<script>try{Typekit.load({ async: true });}catch(e){}</script>
<%= javascript_include_tag :application, 'data-turbolinks-track': 'reload' %>
<%= render 'analytics' %>
<%= yield :javascript %>

app/views/application/_sidebar.html.erb
<aside class="sidebar">
  <% if signed_in? %>
    <%= present(:sidebar, current_user).calendar_list(for_current: @calendar) %>
    <%= present(:sidebar, current_user).invitation_link %>
    <%= present(:sidebar, current_user).calendar_actions %>
    <%= present(:sidebar, current_user).session_actions %>
  <% else %>
    <nav class="signed-out">
      <%= link_to t('helpers.submit.session.create'), new_session_path, class: 'action' %>
      <%= link_to t('helpers.submit.user.create'), new_user_path, class: 'action' %>
    </nav>
  <% end %>
</aside>